config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout',:sign_up => 'register'}
  resources :users
  resources :articles do
    resources :comments
  end

  get 'world', to:'sections#world'

  get '/health', to:'sections#health'

  get '/sports', to:'sections#sports'

  get '/business', to:'sections#business'

  get 'sections/contact'

  post 'sections/thank_you'

  get '/tech', to:'sections#tech'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root'articles#index'
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	belongs_to :user

	def self.get_featured_article
		Article.where(featured_articles: true).order(created_at: :desc)		
	end

	def self.search(search_term)
	  if Rails.env.production?
  		Article.where("name ilike ?", "%#{search_term}%")
  	else
  		Article.where("name LIKE ?", "%#{search_term}%")
  	end 
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index
    if params[:q]
      search_term = params[:q]
      @articles = Article.search(search_term)
      @featured = Article.get_featured_article
    else
      @articles = Article.all.order(created_at: :desc)
      @featured = Article.get_featured_article
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @featured = Article.get_featured_article
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @featured = Article.get_featured_article
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :description, :image_url,:featured_articles,:category)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_featured.html.erb
<div class=" row featured_area">
  <div class="article_panel">
    <%@featured.each do|featured|%>
      <h5 id="top_stories"><%= link_to featured.name, featured %></h5>
  <%end%>
  </div>
  <p class="slide text-center"><div id="pull-me">Top Stories >></div></p>
  <br>
  <%@featured.each do|featured|%>
  	<h4><%=featured.name%></h4>
    <%= link_to featured do %>
       <%= image_tag featured.image_url, class: "img-responsive featured-img" %>
    <% end %>
    <%end%>
</div>
   



app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name ,class: "form-control"%>
  </div>

  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_area :description ,class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :image_url %>
    <%= f.text_field :image_url ,class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :featured_articles%>
    <%= f.text_field :featured_articles ,class: "form-control", placeholder: "true / false" %>
  </div>


  <div class="field form-group">
    <%= f.label :category%>
    <%= f.text_field :category ,class: "form-control",placeholder: "tech / world / health / sports or business" %>
  </div>

  <div class="actions form-group">
    <%= f.submit class: "btn btn-default btn-special"%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="edit_page">
	<h1>Editing Article</h1>
	<%= render 'form', article: @article %>
	<%= link_to 'Show', @article %> |
	<%= link_to 'Back', articles_path %>
</div>

	<%= render 'featured', featured: @featured %>

app/views/articles/index.html.erb
<div class="row index-articles">
  <% @articles.each do |article| %>
    <div class="col-md-6 index_box">
      <h3 id="heading"><%= link_to article.name, article %></h3>

      <%=image_tag(article.image_url,class:"img-responsive")%>
      <p class="description"><%= article.description.html_safe %></p> 

      <div id = "time">
        <p><%= link_to 'Read more >>', article %>
          <% if current_user != nil && current_user.admin? %>
            <%= link_to '| Edit |', edit_article_path(article) %>
            <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?'} %>
          <% end %>
        </p>

        <h6 class="time"><%= article.created_at.to_formatted_s(:long) %>
        <%= "#{time_ago_in_words(article.created_at)} ago" %></h6>
      </div>

      <hr><br>
    </div>  
  <% end %>
 
  <% if current_user != nil && current_user.admin? %>
    <%= link_to 'New Article', new_article_path, class:"btn btn-primary new-art-btn" %>
  <% end %><br><br>
</div>

<%= render 'featured', featured: @featured %>


 

app/views/articles/new.html.erb
<div class="new_page">
	<h1>New Article</h1>
	<%= render 'form', article: @article %>
	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="show_page">
	<h2><%=@article.name%></h2> <br>
    <%=image_tag(@article.image_url,class: "img-responsive show-img")%>

    <p class="description_detail"> <%= @article.description.html_safe %></p> <br>
    <%= "#{time_ago_in_words(@article.created_at)} ago" %><hr>
  
  <% if current_user != nil && current_user.admin? %>
		<%= link_to 'Edit', edit_article_path(@article) %> |
	<%end%>
	<%= link_to 'Back', articles_path %>
</div><br><br>

<%= render 'featured', featured: @featured %>