config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout',:sign_up => 'register'}
  resources :users
  resources :articles do
    resources :comments
  end

  get 'world', to:'sections#world'

  get '/health', to:'sections#health'

  get '/sports', to:'sections#sports'

  get '/business', to:'sections#business'

  get 'sections/contact'

  post 'sections/thank_you'

  get '/tech', to:'sections#tech'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root'articles#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ENews</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noticia+Text" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Gudea" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body>
  	<div class="container">

  		<!-- ========================
  		logo area
  		===================== -->
  		<div  id="logo-area">
  			<%=image_tag("news.png", class: "img-responsive logo-left")%>
  			<!-- search form -->
  			<%= form_tag("/articles", method: "get",class: "input-group search-bar") do %>
				 	<%= text_field_tag(:q, nil, class: "form-control",placeholder: "Search") %>
				  <span class="input-group-btn">
				  	<%= button_tag(type: 'submit', class: "btn search-btn") do %><span class="glyphicon glyphicon-search"></span> 
						<% end %>
					</span> 
				<% end %>
  		</div>
  		

			<!-- ========================
  		nav bar
  		===================== -->
  		<nav class="navbar navbar-inverse">
			  <div class="container-fluid">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
		   			<%= link_to 'Enews',root_path, class: "navbar-brand" %>
			    </div>

			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <ul class="nav navbar-nav">
			        <li class="<%= active_class(root_path) %>"><%= link_to 'HOME',root_path%></li>
			         <li class="<%= active_class(sections_contact_path) %>"><%= link_to 'CONTACT',sections_contact_path%></li>
			        <li class="dropdown  <%= active_class(tech_path) %> <%= active_class(world_path) %> <%= active_class(health_path) %> <%= active_class(sports_path) %> <%= active_class(business_path) %>">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CATEGORY <span class="caret"></span></a>
			          <ul class="dropdown-menu">
			            <li><%= link_to 'Tech',tech_path%></li>
					        <li><%= link_to 'World',world_path%></li>
					        <li><%= link_to 'Health',health_path%></li>
					        <li><%= link_to 'Sports',sports_path%></li>
					        <li><%= link_to 'Business',business_path%></li>
			          </ul>
			        </li>
			      </ul>
			 		
			 			<!-- sign in button -->
			      <ul class="nav navbar-nav navbar-right">
			        <li class="<%= active_class(new_user_registration_path) %>">
			        	<% if user_signed_in? %>
			      			<% link_to new_user_registration_path do %>
								  	<i class="glyphicon glyphicon-user"></i> Sign Up
									<% end %>
							  <% else %>
									<%= link_to new_user_registration_path do %>
								  	<i class="glyphicon glyphicon-user"></i> Sign Up
									<% end %>
								<% end %>
				      </li>

				      <!-- login button -->
							<li class="<%= active_class(new_user_session_path) %>">
							  <% if user_signed_in? %>
							   	<%= link_to destroy_user_session_path, method: :delete do %>
								    <i class="glyphicon glyphicon-log-in"></i> Logout
									<% end %>
							  <% else %>
							   
							    <%= link_to new_user_session_path do %>
								    <i class="glyphicon glyphicon-log-in"></i> Login
									<% end %>
							  <% end %>
							</li>
			      </ul>
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>


			<!-- side nav -->
			
<div id="mySidenav" class="sidenav">
  <a href="#" id="about">About</a>
  <a href="#" id="blog">Blog</a>
  <a href="#" id="projects">Projects</a>
  <a href="#" id="contact">Contact</a>
</div>




			<!-- ========================
  		alerts
  		=====================  -->
  		<div class="articles-area">
  			<% if notice %> 
	  			<div class="alert alert-success glyphicon glyphicon-exclamation-sign fadeout" role="alert">
	  				<%= notice %>
	  			</div>
				<% end %>

				<% if alert %>
	  			<div class="alert alert-danger glyphicon glyphicon-exclamation-sign fadeout" role="alert">
	  				<%= alert %>
					</div>
				<% end %>
				<!-- content -->
  			<%= yield %>
  		</div>
  	</div><!-- container ends here -->
   

  	<!-- ========================
  	footer
  	=====================  --> 
		<div class="footer">
			&#169; 2017 Easha
		</div>
  </body>
</html>